version: '2'

services:
  php:
    build:
      context: ./
      dockerfile: php-apache.dockerfile
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www
    links:
      - db

  db:
    image: mysql:5.7
    volumes:
      - ./sqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database

# Uncomment if sass compilation is needed
#  scss_watch:
#    build:
#      context: ./
#      dockerfile: scss.dockerfile
#    volumes:
#      - ./public/themes/cars/css:/app/scss