version: '2'

services:
  php:
    build: ./ss_docker
    ports:
      - "8080:80"
      - "8443:443"
    links:
      - db
    volumes:
      - ./www:/var/www

  db:
    image: mysql:5.7
    volumes:
      - ./sqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root